apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURERENDQWZTZ0F3SUJBZ0lSQVBqYU94TzROSVhYU05CQVh4bUMwQkF3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa1pqTXhOakZrTkRndE1UTTNNQzAwTVdFMExXRm1aV1V0TURVeE5UbGxOekJsT1dabApNQjRYRFRJd01ETXdOekE1TURjME1Wb1hEVEkxTURNd05qRXdNRGMwTVZvd0x6RXRNQ3NHQTFVRUF4TWtaak14Ck5qRmtORGd0TVRNM01DMDBNV0UwTFdGbVpXVXRNRFV4TlRsbE56QmxPV1psTUlJQklqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBMmlDa25QUnZ3OU1BeE1ka1UwVW94MGwydmpsOVNMYWVqNU11d1Robgo2ZFd3bTRCRFVpM2F0SXQ0aHVSQXB5R2NDTlBSYmxxb3VRSC83WmZPenZLUHBrQkJyY2Rkb2o4YkVZMkpIdzlUCjM0L280ck5CTFB6ZGVYSjRrakdWNHZLTFhwcnBGMXZsS0VlQS9zWWtIMHBXMXprM1pVMnBhcldoWXMzSGE4YVUKN0lIbmw3WlNScTg3eW40S0NOTi9EQi9SN010RXRseGRlUVVyTGsvdUQzOGxNTmphemVyWGs5cCs1YnRSZWZtYgpiZ0RESE9HWCt4blQ2Z08wVXVwb2ZtYU02QTBBemo1ak1Tc2gySUFtd3JsWUZ2dWZleUlSemRUc2l3VDR1YVdSCldpK3pMRUxtUHhFTkJBU0lHZ2doTXZjajMzUDJUSVJqaGRqZjhSMGVWeC84alFJREFRQUJveU13SVRBT0JnTlYKSFE4QkFmOEVCQU1DQWdRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQQpnSXkxeXZTbFkxYjBVYzNlSHhSMHA2SVA4LzQxNGZLdjN3RnBPL05zZitnVm9QTmtSbWd3a2Y4bEljZ2hRMWRyClpTd0ZMSFgwcjRub2psMFpoUGVGYmJ1L29tRFA4b3F3RThaeE0yaEFvcmxLTTFUVW5iMXovYmFieWhxSjFWQ3QKOXBhVThXdnNITVJkQXlMbGVyUVpRNHpQeElpOStyaWRZNDJYQzh1UnBYQzBtTGZlVXROcGdiRzRlc3lvTnJkMwpQR1ZYell6L0xuVUJqZjhGV1lpV0ROWmhjYkhRZko2bUh4bWk5RzhXNXlmc2hoSkNsRkZ4cFhxSGVuSXdKbVFwClZKeExsdUpmUkplWTRia0NjN3BwdFdDb3k4L0Q1bFFYUlM5V25weFhZVUhrWUkzOVUwTmRmQm42aVFidUFPUGEKUmpvZEE1NWhYMjFlalpiTGRJUENVdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://35.230.147.165
  name: cluster-1
contexts:
- context:
    cluster: cluster-1
    user: user-1
  name: my-cluster
current-context: my-cluster
kind: Config
preferences: {}
users:
- name: user-1
  user:
    auth-provider:
      config:
        access-token: ya29.c.KpABwQd-KHcOlm9n9xLbfTYcR0CnFhjUou_fe4uWdnmAnIGT3wXd1NfNSTNZ9bvUhGh4bzd9N6OM6bB1w8WvIX57cqy-FSD0j7bi2MjC3W51bOyc7qD9QC7OFhVOgo3OCcnrsKHhEAH7_EtrakQ8eKCs5VgfXClcT0XgLei-h67aY-pSRQYGltSIEXs3DkHnNbth
        expiry: "2020-03-07T23:14:31.692264961Z"
      name: gcp
